import React from "react";
import { MDBDataTable } from "mdbreact";

const DatatablePage = () => {
  const data = {
    columns: [
      {
        label: "Company Name",
        field: "CompanyName",
        sort: "asc",
        width: 150,
      },
      {
        label: "Email Address",
        field: "Email",
        sort: "asc",
        width: 300,
      },
      {
        label: "Contact Person",
        field: "Phone",
        sort: "asc",
        width: 300,
      },
      {
        label: "Facilitator",
        field: "facility",
        sort: "asc",
        width: 100,
      },
      {
        label: "Sites",
        field: "sites",
        sort: "asc",
        width: 150,
      },
      {
        label: "Tenants",
        field: "tenant",
        sort: "asc",
        width: 100,
      },
      {
        label: "Tenants Groups",
        field: "groups",
        sort: "asc",
        width: 100,
      },
      {
        label: "Actions",
        field: "actions",
        sort: "asc",
        width: 100,
      },
    ],
    rows: [
      {
        CompanyName: "Infosys",
        Email: "management@infosys.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },

      {
        CompanyName: "Wipro",
        Email: "management@wipro.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Accenture",
        Email: "management@accenture.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Capgemini",
        Email: "management@capgemini.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Lodha",
        Email: "management@Lodha.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "TCS",
        Email: "management@tcs.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "HCL",
        Email: "management@HCL.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Redington",
        Email: "management@redington.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Mphasis",
        Email: "management@mphasis.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Larsen & Tourbo",
        Email: "management@larsentourbo.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },

      {
        CompanyName: "Wipro",
        Email: "management@wipro.com",

        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },

      {
        CompanyName: "Infosys",
        Email: "management@infosys.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Accenture",
        Email: "management@accenture.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Capgemini",
        Email: "management@capgemini.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Lodha",
        Email: "management@Lodha.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "TCS",
        Email: "management@tcs.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "HCL",
        Email: "management@HCL.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Redington",
        Email: "management@redington.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Mphasis",
        Email: "management@mphasis.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Larsen & Tourbo",
        Email: "management@larsentourbo.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },

      {
        CompanyName: "Infosys",
        Email: "management@infosys.com",
        Phone: "+91 7869549034",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },

      {
        CompanyName: "Wipro",
        Email: "management@wipro.com",
        Phone: "+91 9876453726",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },

      {
        CompanyName: "Capgemini",
        Email: "management@capgemini.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Accenture",
        Email: "management@accenture.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Lodha",
        Email: "management@Lodha.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "TCS",
        Email: "management@tcs.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "HCL",
        Email: "management@HCL.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Redington",
        Email: "management@redington.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Mphasis",
        Email: "management@mphasis.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
      {
        CompanyName: "Larsen & Tourbo",
        Email: "management@larsentourbo.com",
        Phone: "+91 9876590876",
        person: "Vijayent Roy",
        facility: "--",
        sites: "12",
        tenant: "--",
        groups: "--",
        actions: "",
      },
    ],
  };

  return <MDBDataTable striped bordered small data={data} />;
};

export default DatatablePage;
