 export const data = [
  {
    CompanyName: "Infosys",
    Email: "management@infosys.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },

  {
    CompanyName: "Wipro",
    Email: "management@wipro.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "Accenture",
    Email: "management@accenture.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "Capgemini",
    Email: "management@capgemini.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "Lodha",
    Email: "management@Lodha.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "TCS",
    Email: "management@tcs.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "HCL",
    Email: "management@HCL.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "Redington",
    Email: "management@redington.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "Mphasis",
    Email: "management@mphasis.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
  {
    CompanyName: "Larsen & Tourbo",
    Email: "management@larsentourbo.com",
    Phone: "+91 9876590876",
    person: "Vijayent Roy",
    facility: "--",
    sites: "12",
    tenant: "--",
    groups: "--",
    actions: "",
  },
];
